name: Deploy .NET Web API to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore ./TwoHandApp/TwoHandApp.csproj

    - name: Build app
      run: dotnet build ./TwoHandApp/TwoHandApp.csproj --configuration Release

    - name: Publish app
      run: dotnet publish ./TwoHandApp/TwoHandApp.csproj -c Release -o ./publish

    - name: Deploy via SSH
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        source: ./publish/
        target: /home/${{ secrets.SERVER_USER }}/twohandapp

    - name: Restart app on server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          sudo systemctl restart twohandapp.service
