name: Deploy .NET Web API

on:
  push:
    branches:
      - main  # или твоя основная ветка

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore ./MyApp.sln

    - name: Build
      run: dotnet build ./MyApp.sln --configuration Release --no-restore

    - name: Publish
      run: dotnet publish ./MyApp/MyApp.csproj -c Release -o ./publish --no-build

    - name: Deploy to server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        source: "./publish/"
        target: "/var/www/myapp/"

    - name: Run migrations and restart service
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /var/www/myapp
          dotnet MyApp.dll database update
          sudo systemctl restart myapp.service
